#define BRACKET 1
#define IDENTIFIER 2
#define KEYWORD 3 
#define MATH_OP 4
#define COMPARATOR 5
#define LOGICAL_OP 6
#define BITWISE_OP 7
#define PUNCTUATOR 8
#define ASSIGN_OP 9
#define ASSIGN_BIT 10
#define CONSTANT 11
#define FLOAT 12	
#define BOOL 13
#define STRING 14
#define InOut 15